spring.datasource.hikari:
  connectionTimeout: 20000
  maximumPoolSize: 5
spring.datasource:
  url: jdbc:postgresql://localhost:5432/travelwaka
  username: postgres
  password: postgres
spring.jpa.hibernate.ddl-auto: update
server:
  servlet:
    context-path: /api